root: true
env:
  browser: true
  es2020: true
extends:
  - tuxsnct
  - tuxsnct/react
  - tuxsnct/typescript
parserOptions:
  project: ./tsconfig.json
rules:
  no-undefined: 0
  "@emotion/syntax-preference": [2, "object"]
